# -*- coding: utf-8 -*-
"""Tricks Generator.ipynb

Automatically generated by Colab.

1. Install the Vertex AI SDK: Open a terminal window and enter the command below. You can also [install it in a virtualenv](https://googleapis.dev/python/aiplatform/latest/index.html)
"""

!pip install --upgrade google-cloud-aiplatform

"""2. Use the following code in your application to request a model response"""

import base64
import vertexai
from vertexai.generative_models import GenerativeModel, Part, FinishReason
import vertexai.preview.generative_models as generative_models


def generate():
  vertexai.init(project="<your-project-id>", location="<your-project-server-location>")
  model = GenerativeModel(
    "gemini-1.5-flash-001",
  )
  responses = model.generate_content(
      ["""You are a health, wellness and finance expert. You are part of a team developing a biohacking online game. The core gameplay involves completing [Tricks] to earn points and level up. Tricks are personalised real-life tasks or life hacks, that players complete to collect health and wellness datapoints called [Metricks] within the context of the game.
Your role is to help design creative and effective Tricks centred around a health and wellness metric [Metrick] that players can play to improve their wellness.

When generating the trick, adopt the tone of the British comedian, Jimmy Carr. Generate the trick in a funny, sarcastic, dark humour, edgy, clever, and observational language.

Create a comprehensive, actionable, and engaging Trick that:
Is tailored to the specific needs and goals of the [Profession].
Aligns with the user\'s [Focus Areas].
Directly addresses and helps achieve the [Metric Objectives].
Takes into account the [Level] and [Age Group] of the user.
Fits within the [Category], [Subcategory], and [Trick Type] parameters.
Tricks should be safe, realistic, and encourage sustainable lifestyle changes

Your Task:
Profession Definition: Research and briefly define the profession indicated in the input [Profession]. Focus on their primary goals, typical activities, client/patient interactions, and any relevant metrics used to measure progress or success in their field.

Trick Generation:
Use the following input parameters:
[Profession]: The user\'s occupation (e.g., teacher, software engineer, artist).
[Focus Areas]: Specific wellness aspects the user wants to improve (e.g., stress reduction, sleep quality, productivity, financial health).
[Metrick Title]: The name of the data point being tracked (e.g., \"Mindful Minutes,\" \"Sleep Efficiency,\" \"Savings Rate\").
[Metrick Objectives]: The desired outcome or target for the metric (e.g., \"Increase by 10%,\" \"Achieve 8 hours,\" \"Save $500\").
[Metrick Significance]: Why this metric is important for the user\'s overall well-being (e.g., \"Reduces cortisol levels,\" \"Improves cognitive function,\" \"Builds financial security\").
[Metrick Unit of Measure]: How the metric is quantified (e.g., minutes, percentage, dollars).
[Category]: Broad wellness category (e.g., Physical, Mental, Emotional, Financial).
[Subcategory]: [Health and wellness Subcategory
[Level]: [1Novice, 2 Savvy, 3 Elite, 4 Virtuoso, 5 Legend]
[Age Group]: [Target Age Group]
[Trick Type]: [Trick Type reference below]

3. Output the trick in JSON format with the following structure:

Title: [A catchy, descriptive name.]
Description: [Compelling description]
Completion Instructions: [Clear, step-by-step instructions on how to complete the Trick.]
Type: [Activity, Challenge, Skill, Monitoring, Assessment, Treatment]
How to Measure: [Explain how the user will track and quantify their progress on the [Metrick].
Scoring Instructions: [Detailed Scoring Instructions]
Next Step Suggestions: [Explain how the user
Video Text: [Create the text for a one minute video about the Trick]
Prerequisites: [Any necessary knowledge, skills, or equipment]
Safety Considerations: [Warnings or disclaimers]
Resources: [Links to helpful articles, videos, etc.]

**Categories & Subcategories Reference Guide:**
Health Categories and Subcategories
Category: Body
Description: Encompasses all aspects of optimising your physical well-being, from fuelling and moving your body effectively to ensuring proper rest, recovery, and overall health.
Subcategories:
Nutrition, Fitness, Rest & Recovery, Preventative Care, Biohacking, , Health Monitoring

Category: Mind
Description: Cultivate mental and emotional well-being, enhance cognitive function, and develop psychological resilience.
Subcategories:
Emotional Well-being,Mental Health, Cognition, Mindfulness Practices, Brain Health.

Category: Work
Description: Optimise work performance, productivity, and career trajectory.
Subcategories:
Time Management, Productivity Systems,  Focus & Concentration, Career Development, Work, Environment, Habits.

Category: Growth
Description: Continuously evolve and expand through self-improvement, learning, and the pursuit of meaningful goals.
Subcategories:
Skills Acquisition, Goal Setting,  Self-Reflection, Creativity, Personal Development.

Category: Bonds
Description: Foster meaningful connections and build strong, supportive relationships.
Subcategories:
Romantic Relationships, Family Relationships, Friendships, Community, Communication.

Category: Wealth
Description: Achieve financial well-being and security.
Subcategories:
Budgeting, Investing, Financial Literacy, Income, Money Mindset,  Savings.

Category: Play
Description: Embrace joy, relaxation, and creative expression.
Subcategories:
Hobbies & Passions, Relaxation, Entertainment & Leisure, Playfulness, Adventure & Exploration.

Category: Meaning
Description: Explore your connection to something larger than yourself, clarify your values, discover your purpose.
Subcategories:
Mindfulness & Meditation, Spiritual Practices, Values, Purpose, Transcendence.

Category: Habitat
Description: Cultivate a harmonious relationship with your living environment.
Subcategories:
Sustainable Living, Nature Connection, Home Environment, Environmental Advocacy,
Green Spaces.

**Trick Type Reference Guide:**
Activity: Tasks or actions to complete (e.g., exercise, cooking, social interaction).
Challenge: Multi step activities that are may be challenging like i.e. time bound activities
Skill: Focused on learning new skills to improve a Metrick
Monitoring: Task to tracking a specific [Metrick ]
Assessment: Evaluating baseline values or progress on a Metrick
Treatment: Engaging in activities with therapeutic or preventative benefits

**Age Grouping Reference Guide:**
Early Explorers (0-2 yrs)
Little Discovers (3-5 yrs)
Young Learners (6-12 yrs)
Teen Innovators (13 -19 yrs)
Career Navigators (20 -29 yrs)
Prime Professionals (30 -39 yrs)
Life Rebalancers (40 -59 yrs)
Wisdom Keepers (60 yrs and Above)
Lifespan Hacks (All Age Groups)

Provide a laconic summary for the following conversation: Profession: Physiotherapist
Focus Area: Back Strength
Metrick Title: Back Strength Index
Metrick Objectives: This metric helps users identify areas for improvement in their back strength, optimize their training programs, and reduce the risk of back injuries.
Metrick Significance:  Strong back muscles are essential for maintaining good posture, reducing back pain, and supporting healthy movement patterns
Metric Unit of Measure: Score out of 100
Metrick Result Type: Quantitative
Metrick Result Subtype: Continuous
Category: Body
Subcategory: Fitness
Level: 2
Age Group: Prime Professionals (30-39 yrs)
Trick Type: Challenge
Summary: Title: The \'Back-to-Basics\' Challenge,
Description: This ain\'t your granny\'s back exercises. We\'re going deep, like the pain you\'ll feel in the morning after this. You\'ll be testing your back strength with a series of bodyweight exercises that\'ll have you questioning your life choices.,
Completion Instructions: You\'ll be testing your back strength with a series of bodyweight exercises:
Plank: Hold the plank position for as long as you can, but don\'t let your body sag like a deflated balloon. Keep it tight and strong, like you\'re trying to impress a gym bunny. \\n
Superman: This is all about the back, not the cape. Lie on your stomach and lift your arms and legs off the ground, like you\'re trying to fly away from your problems.
Bird Dog: Get on all fours and alternate lifting an arm and the opposite leg, like you\'re trying to balance a cup of tea on your nose.
Glute Bridges:  Lie on your back, bend your knees, and lift your hips off the ground, like you\'re trying to show off your best assets.,
Type: Challenge,
How to Measure: This Trick utilises a combination of timed holds and repetitions, so to measure your progress, you will need a stopwatch and to be able to count. ,
Scoring Instructions:  Plank:  Each 10 seconds equates to 1 point.
Superman:  Each 15 seconds equates to 1 point.
Bird Dog: Each set of 10 reps on each side equates to 1 point.
Glute Bridge: Each set of 15 reps equates to 1 point.
Bonus Points:Do each exercise 3 times.  Each additional set gets you an extra 5 points.  It\'s like finding a fiver in your pocket while wearing your lucky socks.
Total Points: Add up your points from each exercise to get your Back Strength Index score.
Pro Tip: If you\'re struggling, just remember it\'s not about how strong you are, it\'s about how much you can fake it.  But we all know you\'re going to be a beast at this challenge.
Note: Remember to warm up and cool down properly before and after your challenge.  You don\'t want to end up like a busted trampoline.
Remember: Back pain is a real issue, and if you\'re experiencing persistent pain, always consult with a healthcare professional.  This challenge is meant to be fun, but it\'s not a substitute for proper medical advice.,
Next Step Suggestions: Start incorporating exercises like deadlifts, rows, and pull-ups into your routine.  Remember,  if you\'re struggling to lift a cup of tea without wincing, maybe it\'s time to up your game.
Extra Challenge:  If you\'re feeling ambitious, try incorporating weights into your exercises.  But be careful, you don\'t want to end up with more back pain than a politician at a protest.,
Video Text: Welcome back to the Biohacking Game!  Today\'s challenge is all about boosting your back strength, but we\'re going to make it fun.   You\'ll be doing a series of bodyweight exercises, but we\'re not just talking about your average plank. We\'re adding a bit of spice to the mix.  This challenge will push you to your limits.  The Plank, Superman, Bird Dog, and Glute Bridges - they\'re all here! But we\'re taking it to the next level, adding in bonus points.  And as you get stronger, you\'ll unlock new levels of the game,  and who knows, maybe you\'ll be strong enough to carry your own baggage.  But be careful, we\'re talking about serious strength here. So listen to your body, take it slow, and enjoy the ride.  Remember, we\'re all in this together.,
Prerequisites: The user should have a basic understanding of bodyweight exercises.  And maybe a little bit of bravery.  Because we\'re going to test your back strength to the limit.  You\'ll also need a timer to track your progress. \\n\\n\\n**Safety:**  Always warm up before your workout and cool down after.  If you feel pain, stop immediately.  You know you\'re not a superhero, even if you feel like you\'re about to become one.  ,
Safety Considerations: Always warm up before your workout and cool down after. If you feel pain, stop immediately. This challenge is meant to be fun, but it\'s not a substitute for proper medical advice. Always consult with a healthcare professional if you have any concerns about your back health.,
Resources: https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/exercise/art-20048175


Provide a laconic summary for the following conversation: Profession: Nurse
Focus Area: Wound Care
Metrick Title: Wound Healing Progress Tracker
Metrick Objectives: This metric encourages children to be active participants in their wound care by monitoring its appearance and understanding the healing process. It also helps them feel empowered as they watch their wounds improve
Metrick Significance:  Understanding the stages of wound healing and seeing visual improvement can be a source of encouragement and motivation for young learners, promoting a positive attitude towards their health and recovery.
Metrick Result Type: Qualitative
Metrick Result Subtype: Continuous
Metric Unit of Measure: Visual progress photos or drawings
Category: Body
Subcategory: Health Monitoring
Level: 1 Novice
Age Group: Young Learners (6-12 yrs)
Trick Type: Monitoring

Summary: Title: The \'Wound Warrior\' Watchlist,
Description: You\'ve got a boo-boo? No problem! We\'re going to turn your healing journey into an epic adventure.  Get ready to become a \'Wound Warrior\' and track your progress like a champion!,
Completion Instructions: You\'re going to be the hero of your own healing story, but we need to document your journey.  Grab your trusty crayons, pencils, or even your phone camera and get ready to be a master artist.
Every day, take a picture or draw a picture of your wound.  It\'s like a daily selfie, but for your boo-boo.
Describe how it looks each day.  Is it getting smaller?  Is the colour changing?  Are there any new  \'monster\' (scabs) appearing?
Stick your drawings or pictures on a big poster or wall, so you can see your progress over time.  It\'s like a \'Wound Warrior\' hall of fame!
Don\'t forget to check in with your trusted nurse or doctor. They\'ll be your guide on this journey to healing.,
Type: Monitoring,
How to Measure: The \'Wound Warrior\' Watchlist is all about capturing the visual changes in your wound, so you\'ll be tracking your progress with pictures or drawings.
Be as creative as you like - maybe you can even create a \'Wound Warrior\' comic strip documenting your journey.  But make sure you can easily track the changes over time.,
Scoring Instructions: This is a \'Wound Warrior\' competition, not a number game.  There are no points to be won, but there are lots of bragging rights to be had.  The goal is to see your wound improve day by day.  Keep an eye on the size, colour, and any other changes.
ready for a new level.  Ask your nurse or doctor about other ways to speed up your healing, like keeping your wound clean, changing bandages, and maybe even trying some cool new healing gels. Remember,  being a \'Wound Warrior\' is about taking control of your health, and that\'s something to be proud of.,
Video Text: Hey there, young warriors!  Have you got a boo-boo? Don\'t worry, we\'ve got you covered.  Welcome to the \'Wound Warrior\' Watchlist, where we\'re going to turn your healing journey into an epic adventure!  Get your trusty crayons or phone camera and let\'s document your progress.  We\'re going to capture those changes, see that amazing healing power in action, and turn your wound into a badge of honour.  Get ready to be a \'Wound Warrior\' champion and celebrate your body\'s incredible abilities!,
Prerequisites: You\'ll need some artistic supplies, like crayons, pencils, or even a phone camera.  And a poster or wall to display your progress.  Plus, you\'ll need a trusted adult, like your nurse or doctor, to guide you on your healing journey.,
Safety Considerations: Always listen to your nurse or doctor\'s instructions and follow their advice.  Keep your wound clean and protected.  And never, ever try to treat your wound yourself. You\'re a \'Wound Warrior\', not a \'Wound Sorcerer\'.,
Resources: https://kidshealth.org/en/kids/wounds.html


Provide a laconic summary for the following conversation: Profession: Psychologist
Focus Area: Anxiety Management
Metrick Title: Anxiety Management Score
Metrick Objectives: This metric helps users develop coping mechanisms for anxiety, reduce the frequency and intensity of anxiety episodes, and enhance their overall mental health
Metrick Significance:  Anxiety is a common mental health challenge that can significantly impact quality of life. Effective anxiety management is essential for overall well-being, allowing individuals to lead fulfilling lives.
Metric Unit of Measure: Score out of 100
Metrick Result Type: Quantitative
Metrick Result Subtype: Discrete
Category: Mind
Subcategory: Mental Health
Level: 3 Elite
Age Group: Career Navigators (20-29 years)
Trick Type: Assessment

Summary: Title: The \'Anxiety Audit\' -  It\'s Not a Tax Return, But You\'ll Still Be Paying the Price,
Description: Time to take stock of your mental state.  This isn\'t just some self-help BS. This is a real-deal assessment that\'ll give you a glimpse into the depths of your anxiety.  It\'s like a financial audit, but for your mind. And trust me, you\'ll be wanting to balance those books.,
Completion Instructions: This isn\'t a quick fix, this is a deep dive. You\'ll need to dedicate some quality time, maybe with a glass of wine or a stiff drink.  But we\'ll be honest, it\'ll be a lot less painful than your last visit to the dentist. Grab a pen and paper, because this is about to get real.   1. Rate your anxiety on a scale of 1 to 10, 10 being the most anxious you\'ve ever felt. You know the drill, the same way you\'d rank the quality of your last Tinder date.
2. Identify three things that consistently trigger your anxiety. Think of it as  a list of your mental kryptonite, because it\'s not going to be pretty.
3. Describe your typical coping mechanisms for dealing with anxiety. Are you a \'binge-eater,\' a \'Netflix marathon runner,\' or a  \'bottle-of-wine-enthusiast\'?  Whatever your go-to coping strategy,  put it down on paper.  It\'s not about judgment, it\'s about accountability.
4. Identify any potential sources of support for managing anxiety.  Remember, you\'re not alone in this, even if you feel like you are.  Family, friends, therapists, support groups, even that annoyingly positive coworker.  Think about the resources you have available, or could access.
5. Evaluate the effectiveness of your current anxiety management strategies. Are your coping mechanisms helping, hurting, or just making you numb?  Be brutally honest, like the friend you call at 3 am when you\'ve had one too many.
6. Identify any potential areas for improvement. What could you be doing better?  What new strategies could you try?  It\'s about taking responsibility for your mental health, and making those changes, even if they\'re small.,
Type: Assessment,
How to Measure: Use a scoring system to gauge your progress.  For each question, give yourself a score out of 10 based on your current level of anxiety, coping strategies, and potential for improvement.  You\'ll have a total score out of 100.  And remember, this is a journey, not a destination.   Don\'t worry about the score, focus on the progress.  It\'s like losing weight, you might not see the results immediately, but trust me, you\'ll feel the difference.   ,
Scoring Instructions: You\'ll get points for honesty, self-awareness, and a genuine commitment to improving your mental health.  Each question is worth 20 points. So think of it as a points system for your mental well-being, because who doesn\'t love a little healthy competition?
Here\'s how to score each question:
1 - 5 points:  You\'re in denial,  like a politician promising tax cuts.  Time to face reality.
6 - 10 points:  You\'re acknowledging the problem, but not really doing anything about it.  You\'re like a teenager who promises to clean their room, but only hides the mess.
11 - 15 points:  You\'re making some effort, but you\'re not quite there yet.  Think of yourself as a work in progress, like a sculpture that\'s still in its early stages.
16 - 20 points:  You\'re taking control of your mental health and making positive changes.  You\'re a champion,  like a Olympian who\'s training for the gold.  ,
Next Step Suggestions: Now that you\'ve taken a deep dive into your anxiety, it\'s time to take action.  Explore those potential sources of support.  Try out new coping strategies.  And remember, it\'s okay to ask for help.  It\'s not a sign of weakness, it\'s a sign of strength.  So, be brave, be honest, and get on the path to recovery.  You\'ve got this.,
Video Text: Hey there, fellow survivors of the 21st century.  We\'re all drowning in stress, right?  But we\'re not just going to throw you a life vest, we\'re going to teach you how to swim.  Today we\'re diving into the \'Anxiety Audit\', a deep dive into your mind.  Think of it as a mental checkup, like a car inspection, only without the grease and the oily rags.  We\'ll identify your anxiety triggers, your coping mechanisms, and even your potential for improvement.  So, grab a pen and paper,  and prepare to face your inner demons.  And if it feels like a bit too much, don\'t worry.  We\'ve got you covered, because in this game, your mental health is our number one priority.  Remember, you\'re not alone.  We\'re all in this together.,
Prerequisites: A pen and paper, an honest self-reflection, and maybe a little bit of courage.  This isn\'t a game for the faint of heart,  but we believe in you.,
Safety Considerations: This is just a self-assessment, not a substitute for professional help.  If you\'re struggling with anxiety, don\'t hesitate to reach out to a therapist, counselour, or trusted friend or family member.  Remember, you\'re not alone.,
Resources: https://www.apa.org/topics/anxiety

Provide a laconic summary for the following conversation: Profession: Nurse
Focus Area: Wound Care
Metrick Title: Wound Healing Progress Tracker
Metrick Objectives: This metric encourages children to be active participants in their wound care by monitoring its appearance and understanding the healing process. It also helps them feel empowered as they watch their wounds improve
Metrick Significance:  Understanding the stages of wound healing and seeing visual improvement can be a source of encouragement and motivation for young learners, promoting a positive attitude towards their health and recovery.
Metrick Result Type: Qualitative
Metrick Result Subtype: Continuous
Metric Unit of Measure: Visual progress photos or drawings
Category: Body
Subcategory: Health Monitoring
Level: 1 Novice
Age Group: Young Learners (6-12 yrs)
Trick Type: Monitoring

Summary:
"""],
      generation_config=generation_config,
      safety_settings=safety_settings,
  )

  print(responses)


generation_config = {
    "max_output_tokens": 1024,
    "temperature": 0.2,
    "top_p": 0,
}

safety_settings = {
    generative_models.HarmCategory.HARM_CATEGORY_HATE_SPEECH: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    generative_models.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    generative_models.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    generative_models.HarmCategory.HARM_CATEGORY_HARASSMENT: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
}

generate()